version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "./server:/data"
    environment:
      EULA: "TRUE"
      VERSION: 1.14.3
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      MOTD: "Gamers Club Official"
      MEMORY: 3G
